services:
  - type: web
    name: blog-backend
    runtime: java
    rootDir: blog-backend
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/blog-backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JWT_SECRET
        value: mySuperSecretKey2024!
